# Generated by Django 6.0 on 2026-02-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartexamrecord',
            name='exam_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of compartment exam', null=True),
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='exam_date_notified',
            field=models.BooleanField(default=False, help_text='Has exam date notification been sent?'),
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for compartment registration', null=True),
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='registration_deadline_notified',
            field=models.BooleanField(default=False, help_text='Has registration deadline notification been sent?'),
        ),
    ]
