# Generated by Django 6.0 on 2026-02-06 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_compartexamrecord_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compartexamrecord',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterUniqueTogether(
            name='compartexamrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='gpa_at_failure',
            field=models.FloatField(blank=True, help_text="Student's GPA when they failed this subject", null=True),
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='semester',
            field=models.IntegerField(default=1, help_text='Semester in which student failed the subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(blank=True, default=1, help_text="Student's current semester", null=True),
        ),
        migrations.AlterField(
            model_name='compartexamrecord',
            name='grade',
            field=models.CharField(default='F', help_text='The grade received (typically F)', max_length=5),
        ),
        migrations.AlterField(
            model_name='compartexamrecord',
            name='is_cleared',
            field=models.BooleanField(default=False, help_text='Did student clear the compartment exam?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(blank=True, default=0.0, help_text='Latest or overall GPA', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='compartexamrecord',
            unique_together={('student', 'subject_code', 'semester', 'grade')},
        ),
    ]
