# Generated by Django 6.0 on 2026-02-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_compartexamrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compartexamrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compartexamrecord',
            name='year',
            field=models.IntegerField(default=1, help_text='Academic year in which student failed (1-4)'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(blank=True, default=1, help_text="Student's current year (1-4)", null=True),
        ),
        migrations.AlterField(
            model_name='compartexamrecord',
            name='grade',
            field=models.CharField(default='F', help_text='The grade received (typically F or INC)', max_length=5),
        ),
        migrations.AlterField(
            model_name='compartexamrecord',
            name='semester',
            field=models.IntegerField(default=1, help_text='Semester in which student failed the subject (1-8)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(blank=True, default=1, help_text="Student's current semester (1-8)", null=True),
        ),
        migrations.AlterUniqueTogether(
            name='compartexamrecord',
            unique_together={('student', 'subject_code', 'year', 'semester', 'grade')},
        ),
        migrations.AddIndex(
            model_name='compartexamrecord',
            index=models.Index(fields=['student', 'year', 'semester'], name='students_co_student_cc2f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='compartexamrecord',
            index=models.Index(fields=['semester', 'is_cleared'], name='students_co_semeste_f60cd1_idx'),
        ),
    ]
