# Generated by Django 6.0 on 2026-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_compartexamrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Subject code (e.g., COMP102, MATH101)', max_length=50, unique=True)),
                ('subject_name', models.CharField(blank=True, help_text='Full subject name', max_length=100)),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Registration deadline for compartment exam', null=True)),
                ('exam_date', models.DateTimeField(blank=True, help_text='Date and time of compartment exam', null=True)),
                ('exam_duration_minutes', models.IntegerField(default=180, help_text='Duration of exam in minutes')),
                ('registration_alert_days_before', models.IntegerField(default=7, help_text='Send registration deadline alert X days before deadline')),
                ('exam_alert_days_before', models.IntegerField(default=3, help_text='Send exam schedule alert X days before exam')),
                ('exam_alert_hours_before', models.IntegerField(default=24, help_text='Also send exam reminder X hours before exam (if different from days)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this compartment active?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for this compartment exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compartment Exam Configuration',
                'verbose_name_plural': 'Compartment Exam Configurations',
                'ordering': ['subject_code'],
            },
        ),
    ]
