# Generated by Django 5.2.9 on 2025-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(help_text="e.g., 'Fall 2025 Compart Exam'", max_length=100)),
                ('semester_affected', models.IntegerField(help_text='The semester the failed subjects belong to.')),
                ('form_deadline', models.DateField(help_text='The final date for form submission.')),
                ('alert_date', models.DateField(blank=True, help_text='Calculated date (7 days before deadline) for sending the alert.', null=True)),
                ('is_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExamDeadline',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
