# Generated by Django 5.2.9 on 2025-12-11 16:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='batch',
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Used for automated notifications.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CompartExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(default='F', max_length=5)),
                ('gpa_sheet_file', models.CharField(blank=True, max_length=255)),
                ('is_cleared', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compart_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'subject_code', 'grade')},
            },
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
