# Generated by Django 6.0 on 2026-01-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_scannedresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
