# Generated by Django 6.0 on 2026-01-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
